#! /usr/bin/python
import RPi.GPIO as GPIO

import argparse
import time
import sys


parser = argparse.ArgumentParser(description="Test a GPIO pin")

parser.add_argument('pin', type=int, nargs=1, help='The GPIO pin to trigger')
parser.add_argument('--timeon', type=int, required=False, default=3, help='Amount of seconds to keep pin HIGH (default 3)')
parser.add_argument('--timeoff', type=int, required=False, default=1, help='Amount of seconds to keep pin LOW (default 1')


args = parser.parse_args()

pin = args.pin
timeon = args.timeon
timeoff = args.timeoff

while True:
    GPIO.setmode(GPIO.BCM)
    GPIO.setwarnings(False)
    GPIO.setup(pin,GPIO.OUT)
    print "GPIO pin %s on" % pin
    GPIO.output(pin,GPIO.HIGH)
    time.sleep(timeon)
    print "GPIO pin %s off" % pin
    GPIO.output(pin,GPIO.LOW)
    time.sleep(timeoff)

